### ISSUE TITLE
Development Road map

### ISSUE THREAD

**Issue by dharwishr** [dharwishr/taskie-todo#1]
- [x] #2
  - [x] Rails
  - [x] Webpacker
  - [x] React.js
  - [x] Tailwind
  - [x] Database
- [x] #4
  - [x] Task Model and Controller
  - [x] User Model and Controller
  - [x] Home Controller
  - [x]  API Responder and Exception functions
- [x] #7
  - [x] Navigation Bar
  - [x] Login page
  - [x] Signup page
  - [x] Dashboard 
  - [x] API Connectors 
  - [x] Session Controller
  - [x] Form (Add, Edit)
- [x] #10 
- [x] #13
- [x] #15
- [x] #17
